retail_supply_chain_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "placeholder"
      user: "placeholder"
      role: "<YOUR_ROLE>"
      database: "RETAIL_SUPPLY_CHAIN_DB"
      warehouse: "RETAIL_SUPPLY_CHAIN_QS_WH"
      schema: "PUBLIC"
      threads: 4
      query_tag: '{"dbt_project": "retail_supply_chain_dbt", "environment": "dev"}'
